export const TOPICS: Record<string, { title: string; sideA: string; sideB: string }> = {
  t1: { title: 'Virat Kohli vs Rohit Sharma', sideA: 'Virat Kohli', sideB: 'Rohit Sharma' },
  t2: { title: 'Messi vs Ronaldo', sideA: 'Messi', sideB: 'Ronaldo' },
  t3: { title: 'Football vs Cricket', sideA: 'Football', sideB: 'Cricket' },
  t4: { title: 'LeBron vs Jordan', sideA: 'LeBron James', sideB: 'Michael Jordan' },
  t5: { title: 'Test Cricket vs T20', sideA: 'Test Cricket', sideB: 'T20' },
  t6: { title: 'Marvel vs DC', sideA: 'Marvel', sideB: 'DC' },
  t7: { title: 'Interstellar vs Inception', sideA: 'Interstellar', sideB: 'Inception' },
  t8: { title: 'Nolan vs Scorsese', sideA: 'Nolan', sideB: 'Scorsese' },
  t9: { title: 'Anime vs Western Cartoons', sideA: 'Anime', sideB: 'Western Cartoons' },
  t10: { title: 'Movies vs TV Shows', sideA: 'Movies', sideB: 'TV Shows' },
  t11: { title: 'Android vs iPhone', sideA: 'Android', sideB: 'iPhone' },
  t12: { title: 'AI is good vs bad for humanity', sideA: 'Good', sideB: 'Bad' },
  t13: { title: 'Remote Work vs Office Work', sideA: 'Remote Work', sideB: 'Office Work' },
  t14: { title: 'Social Media helps vs hurts society', sideA: 'Helps', sideB: 'Hurts' },
  t15: { title: 'Electric Cars vs Petrol Cars', sideA: 'Electric', sideB: 'Petrol' },
  t16: { title: 'PC vs Console Gaming', sideA: 'PC', sideB: 'Console' },
  t17: { title: 'PUBG vs Free Fire', sideA: 'PUBG', sideB: 'Free Fire' },
  t18: { title: 'Single Player vs Multiplayer', sideA: 'Single Player', sideB: 'Multiplayer' },
  t19: { title: 'Minecraft vs Roblox', sideA: 'Minecraft', sideB: 'Roblox' },
  t20: { title: 'Gym vs Calisthenics', sideA: 'Gym', sideB: 'Calisthenics' },
  t21: { title: 'Early Bird vs Night Owl', sideA: 'Early Bird', sideB: 'Night Owl' },
  t22: { title: 'Vegetarian vs Non-Vegetarian', sideA: 'Vegetarian', sideB: 'Non-Vegetarian' },
  t23: { title: 'Books vs Podcasts', sideA: 'Books', sideB: 'Podcasts' },
  t24: { title: 'City Life vs Village Life', sideA: 'City Life', sideB: 'Village Life' },
  t25: { title: 'Drake vs Kendrick Lamar', sideA: 'Drake', sideB: 'Kendrick Lamar' },
  t26: { title: 'Hip Hop vs Rock', sideA: 'Hip Hop', sideB: 'Rock' },
  t27: { title: 'Spotify vs YouTube Music', sideA: 'Spotify', sideB: 'YouTube Music' },
  t28: { title: 'Live Music vs Studio Albums', sideA: 'Live Music', sideB: 'Studio Albums' },
  t29: { title: 'College Degree vs Self-Taught', sideA: 'College Degree', sideB: 'Self-Taught' },
  t30: { title: 'Job Security vs Startup Risk', sideA: 'Job Security', sideB: 'Startup Risk' },
  t31: { title: 'Passion vs Salary', sideA: 'Follow Passion', sideB: 'Follow Salary' },
  t32: { title: 'Entrepreneur vs Employee', sideA: 'Entrepreneur', sideB: 'Employee' },
}

export const SUGGESTIONS: Record<string, string[]> = {
  t1: ['Who has the better ODI record?', 'Who performs better under pressure?', 'Who would you pick for a World Cup final?'],
  t2: ['Who has more natural talent?', 'Who elevated their team more?', 'Who had the better peak season?'],
  t3: ['Which requires more skill?', 'Which is more exciting to watch?', 'Which has a bigger global impact?'],
  t4: ['Who had the better peak?', 'Who is the better leader?', 'Who would you build a team around?'],
  t5: ['Which is better for the sport?', 'Which is more skillful?', 'Which do you enjoy watching more?'],
  t6: ['Which has better character development?', 'Which cinematic universe is more consistent?', 'Best standalone film from each?'],
  t7: ['Which had a better ending?', 'Which is more rewatchable?', 'Which had a bigger cultural impact?'],
  t8: ['Who has more artistic range?', 'Who has the better filmography?', 'Best film from each director?'],
  t9: ['Which has better storytelling?', 'Which has more cultural depth?', 'Which has better animation?'],
  t10: ['Which is better for storytelling?', 'Which offers more value?', 'Which do you prefer on weekends?'],
  t11: ['Which has better privacy?', 'Which is better value for money?', 'Which ecosystem is more useful?'],
  t12: ['Will AI take more jobs than it creates?', 'Can AI be truly creative?', 'Should AI development be regulated?'],
  t13: ['Which is better for productivity?', 'Which is better for mental health?', 'Which is the future of work?'],
  t14: ['Has social media helped movements?', 'Is social media making us lonelier?', 'Should social media be regulated?'],
  t15: ['Which is better for the environment?', 'Which is more practical today?', 'Which will dominate in 10 years?'],
  t16: ['Which has better exclusives?', 'Which is better for multiplayer?', 'Which offers more value long term?'],
  t17: ['Which has better gameplay?', 'Which has a better community?', 'Which is more competitive?'],
  t18: ['Which offers more replayability?', 'Which is more fun with friends?', 'Which has better game design?'],
  t19: ['Which is more creative?', 'Which has a better community?', 'Which is better for kids?'],
  t20: ['Which builds more functional strength?', 'Which is more accessible?', 'Which is better for long term health?'],
  t21: ['Which is more productive?', 'Which is better for creativity?', 'Which suits modern life better?'],
  t22: ['Which is healthier?', 'Which is better for the environment?', 'Which is more sustainable long term?'],
  t23: ['Which helps you learn faster?', 'Which is better for deep focus?', 'Which fits better into daily life?'],
  t24: ['Which is better for raising a family?', 'Which offers better quality of life?', 'Which would you choose permanently?'],
  t25: ['Who has the better discography?', 'Who has had more cultural impact?', 'Who won the beef?'],
  t26: ['Which has more artistic depth?', 'Which has better live performances?', 'Which will last longer?'],
  t27: ['Which has better sound quality?', 'Which has the better library?', 'Which is better value?'],
  t28: ['Which is more authentic?', 'Which shows more artistry?', 'Which do you prefer?'],
  t29: ['Which opens more doors?', 'Which is better ROI?', 'Which is better for tech careers?'],
  t30: ['Which makes you happier long term?', 'Which is smarter financially?', 'Which would you choose at 25?'],
  t31: ['Can passion pay the bills?', 'Does salary lead to passion?', 'What did you choose?'],
  t32: ['Which gives more freedom?', 'Which is more financially stable?', 'Which would you choose?'],
}